Don't crash when modifying an alert with an event
If an alert is modified containing only and event without either a
condition or method python gvm crashed by raising a `AttributeError:
'NoneType' object has no attribute 'name'`. With this change it has been
made obvious that a condition and method is required too.